config/routes.rb
Rails.application.routes.draw do
  #mount ActionCable.server => '/cable'

  # Para el restablecimiento de contraseña desde el login
  devise_for :users, :skip => [:registrations], controllers: {
    registrations: 'registrations',
    passwords: 'passwords'  # Opcional: si quieres personalizar el controlador de contraseñas
  }

  # Para el cambio de contraseña desde el perfil
  as :user do
    get 'users/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'registrations#update', :as => 'user_registration'
  end

  # Luego tus rutas personalizadas
  resources :users, only: [:update]
  get 'users/profile'
  get 'users/change_password_modal', to: 'users#change_password_modal'

  resources :events, except: [:destroy] do
    resources :victims, except: [:index, :show]
    resources :event_actions, except: [:index, :show]
    resources :resource_requests, except: [:destroy, :show, :edit, :update] do
      get :cancel
    end
    member do
      delete 'sketch/:image_id', to: 'events#destroy_sketch', as: 'destroy_sketch'
      delete 'organization_chart/:image_id', to: 'events#destroy_organization_chart', as: 'destroy_organization_chart'
    end
    get :export_201
    get :export_207
    get :export_211
    get :close_event_modal
    post :close_event
  end

  resources :resource_requests, only: [:index, :new, :create] do
    resources :assist_requests, only: [:new, :create]
  end

  resources :assist_requests, only: [] do
    collection do
      post :create_assist
    end
    get :arrive_modal
    put :arrive
    get :demobilize_modal
    put :demobilize
    get :state_modal
    put :change_state
  end

  resources :user_permissions, :except => [:destroy, :show]

  resources :resources, :except => [:destroy, :show] do
    collection do
      get :search_resources
    end
  end

  resources :organizations, :except => [:destroy] do
    resources :resource_per_organizations, :except => [:destroy, :show]
  end

  resources :notifications, only: [:index, :show] do
    collection do
      get :mark_as_read
    end
  end

  get 'reports/report'
  root to: 'dashboard#index'
  get 'dashboard/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    org_id = current_user.organization_id
    @show_organizations = params[:show_organizations].present?
    @events = Event.mappable_events
    @organizations = Organization.mappable_organizations if @show_organizations
    @scheduled_events = Event.uninitialized_events.by_organization(org_id)
    @resource_requests = ResourceRequest.active
                                        .where(organization_id: [nil, org_id])
                                        .includes(:resource_request_items).order(created_at: :desc)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_resource_requests.html.erb
<div class="card border-0 shadow flex-grow-1">
  <div class="card-header border-bottom d-flex align-items-center justify-content-between">
    <h2 class="fs-5 fw-bold mb-0">Solicitudes de recursos</h2></div>
  <div class="card-body overflow-y-auto p-0">
    <div class="accordion accordion-flush mt-2" id="resourceRequestAccordion">
      <%= render @resource_requests %>
    </div>
  </div>
</div>

app/views/dashboard/_scheduled_event.html.erb
<div class="accordion-item center-marker" data-action="click->map#centerMarker" data-id="<%= scheduled_event.id %>" >
  <h2 class="accordion-header" id="event-heading-<%= scheduled_event.id %>">
    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#event-collapse-<%= scheduled_event.id %>" aria-expanded="false" aria-controls="collapseOne">
      <%= scheduled_event.name %>
      <%- if scheduled_event.organizer? current_user %>
        <span class="d-block ms-2 my-1 badge rounded-pill bg-success text-white">Organizador</span>
      <% end %>
    </button>
  </h2>
  <div id="event-collapse-<%= scheduled_event.id %>" class="accordion-collapse collapse" aria-labelledby="event-heading-<%= scheduled_event.id %>" data-bs-parent="#scheduledEventsAccordion">
    <div class="accordion-body">
      <div class="mb-1"><b>Inicio:</b> <%= scheduled_event.event_start&.strftime("%d-%m-%Y %H:%M") %></div>
      <div class="mb-1"><b>Cierre aproximado:</b> <%= scheduled_event.event_end&.strftime("%d-%m-%Y %H:%M") %></div>
      <div class="mb-1"><b>Direcci&oacute;n:</b> <%= scheduled_event.location %></div>
      <div class="text-end">
        <%= link_to 'Ver', event_path(scheduled_event), class: 'btn btn-sm btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_scheduled_events.html.erb
<div class="card border-0 shadow height-300 mb-3">
  <div class="card-header border-bottom d-flex align-items-center justify-content-between">
    <h2 class="fs-5 fw-bold mb-0">Pr&oacute;ximos eventos</h2>
  </div>
  <div class="card-body overflow-y-auto p-0">
    <div class="accordion accordion-flush mt-2" id="scheduledEventsAccordion">
      <%= render partial: 'dashboard/scheduled_event', collection: @scheduled_events %>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="row" data-controller="map">
  <div class="col-12 col-xl-4 d-flex flex-column height-90vh">
    <%= render 'scheduled_events' %>
    <%= render 'resource_requests' %>
  </div>
  <div class="col-12 col-xl-8 d-flex flex-column ">
    <%- @events&.each do |event| %>
      <div data-map-target="marker" data-id="<%= event.id %>" data-lat="<%= event.latitude %>" data-lng="<%= event.longitude %>" data-title="<%= event.name %>" data-icon="<%= asset_path(event.incident? ? 'map_icons/icon_incident.svg' : 'map_icons/icon_event.svg') %>" data-url="<%= event_path(event) %>"></div>
    <% end %>
    <%- @organizations&.each do |org| %>
      <div data-map-target="marker" data-lat="<%= org.latitude %>" data-lng="<%= org.longitude %>" data-title="<%= org.name %>" data-icon="<%= asset_path("map_icons/#{org.custom_icon || 'icon1.svg'}") %>" data-url="<%= organization_path(org) %>"></div>
    <% end %>
    <div class="d-flex align-items-center">
      <%= form_tag(dashboard_index_path, method: :get, class: 'd-flex me-auto') do %>
        <div class="form-check form-switch">
          <label class="form-check-label m-0" for="show_organizations">Mostrar organizaciones</label>
          <%= check_box_tag 'show_organizations', '1', @show_organizations, class:'form-check-input', onchange: 'this.form.submit();' %>
        </div>
      <% end %>

      <%= link_to "Programar Evento", new_event_path(kind: Event.kind.event), class: 'btn btn-outline-primary mt-2 mx-2 animate-up-2' %>
      <%= link_to "Crear Incidente", new_event_path, class: 'btn btn-gray-800 mt-2 animate-up-2' %>
    </div>

    <div data-map-target="map" class="height-80vh mt-2"></div>
  </div>
</div>