config/routes.rb
Rails.application.routes.draw do
  #mount ActionCable.server => '/cable'

  # Para el restablecimiento de contraseña desde el login
  devise_for :users, :skip => [:registrations], controllers: {
    registrations: 'registrations',
    passwords: 'passwords'  # Opcional: si quieres personalizar el controlador de contraseñas
  }

  # Para el cambio de contraseña desde el perfil
  as :user do
    get 'users/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'registrations#update', :as => 'user_registration'
  end

  # Luego tus rutas personalizadas
  resources :users, only: [:update]
  get 'users/profile'
  get 'users/change_password_modal', to: 'users#change_password_modal'

  resources :events, except: [:destroy] do
    resources :victims, except: [:index, :show]
    resources :event_actions, except: [:index, :show]
    resources :resource_requests, except: [:destroy, :show, :edit, :update] do
      get :cancel
    end
    member do
      delete 'sketch/:image_id', to: 'events#destroy_sketch', as: 'destroy_sketch'
      delete 'organization_chart/:image_id', to: 'events#destroy_organization_chart', as: 'destroy_organization_chart'
    end
    get :export_201
    get :export_207
    get :export_211
    get :close_event_modal
    post :close_event
  end

  resources :resource_requests, only: [:index, :new, :create] do
    resources :assist_requests, only: [:new, :create]
  end

  resources :assist_requests, only: [] do
    collection do
      post :create_assist
    end
    get :arrive_modal
    put :arrive
    get :demobilize_modal
    put :demobilize
    get :state_modal
    put :change_state
  end

  resources :user_permissions, :except => [:destroy, :show]

  resources :resources, :except => [:destroy, :show] do
    collection do
      get :search_resources
    end
  end

  resources :organizations, :except => [:destroy] do
    resources :resource_per_organizations, :except => [:destroy, :show]
  end

  resources :notifications, only: [:index, :show] do
    collection do
      get :mark_as_read
    end
  end

  get 'reports/report'
  root to: 'dashboard#index'
  get 'dashboard/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  audited
  extend Enumerize
  include NotificationsHelper

  belongs_to :organization
  has_many_attached :sketchs do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end
  has_many_attached :organization_charts do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end
  has_many :event_actions
  has_many :victims
  has_many :resource_requests
  has_many :assist_requests
  accepts_nested_attributes_for :event_actions,
                                reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :victims,
                                reject_if: :all_blank, allow_destroy: true
  enumerize :kind, in: [:event, :incident], scope: :shallow

  validates :name, :organization_id, presence: true

  scope :active_events, -> { where(closed: [nil, false]) }
  scope :mappable_events, -> { active_events.where.not(longitude: nil) }
  scope :uninitialized_events, -> { active_events.where(kind: Event.kind.event, initialized: [nil, false]) }
  scope :by_organization, -> (org_id) { includes(:assist_requests).where(organization_id: org_id).or(where(assist_requests: {organization_id: org_id})) }

  attr_accessor :demobilization_date, :demobilizing_person, :comments
  before_save :check_organization_changes

  def self.ransackable_attributes(auth_object = nil)
    %w[name organization_id kind closed event_start event_end location commander]
  end

  def incident?
    kind == Event.kind.incident
  end

  def organizer?(user)
    organization_id == user.organization_id
  end

  def close_and_demobilize(params)
    ActiveRecord::Base.transaction do
      # cancel requests
      ResourceRequest.requests_to_demobilize(id).update_all(status: ResourceRequest.status.demobilized)

      # demobilize all resources
      resources_to_demobilize = AssistRequest.resources_to_demobilize(id)
      resources_to_demobilize.each{ |assist| assist.demobilize(params, false)}

      # create event action
      description = "El incidente fue CERRADO por #{params['demobilizing_person']}."
      description += " Fueron desmovilizados automáticamente los recursos: #{resources_to_demobilize.pluck(:code).join(', ')}" if resources_to_demobilize.any?
      EventAction.create(
        description: description,
        date: params['demobilization_date'],
        event: self
      )
      update(closed: true, event_end: params['demobilization_date'])
    end
  end

  private

  def check_organization_changes
    notify_assigned_event(organization_id_was, self) if organization_id_changed? && id.present?
  end
end

app/models/event_action.rb
class EventAction < ApplicationRecord
  belongs_to :event
  validates :date, :description, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource
  include NotificationsHelper
  before_action :set_event, only: %i[ show edit update destroy destroy_sketch destroy_organization_chart]
  before_action :add_index_breadcrumbs, only: [:show, :edit, :new]

  # GET /events or /events.json
  def index
    @q = Event.ransack(params[:q] || {})
    @q.closed_null = true if params[:q].nil?
    @q.sorts = ['event_start desc'] if @q.sorts.empty?
    @events = @q.result.page(params[:page]).per(@per_page)
    add_breadcrumbs('Eventos e Incidentes')
  end

  # GET /events/1 or /events/1.json
  def show
    @organization_id = current_user.organization_id
    @event_actions = @event.event_actions.order(date: :desc)
    @victims = @event.victims.order(created_at: :desc)
    @resource_requests = @event.resource_requests.includes(:resource_request_items).order(:status, created_at: :desc)
    add_breadcrumbs(@event.name)
  end

  # GET /events/new
  def new
    @organization_id = current_user.organization_id
    @event = Event.new(event_actions: [EventAction.new], kind: params[:kind] || Event.kind.incident, organization_id: current_user.organization_id)
    add_breadcrumbs('Nuevo')
  end

  # GET /events/1/edit
  def edit
    @organization_id = current_user.organization_id
    add_breadcrumbs(@event.name, event_path(@event))
    add_breadcrumbs('Editar')
  end

  # POST /events or /events.json
  def create
    @organization_id = current_user.organization_id
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        notify_assigned_event(@organization_id, @event) if @organization_id != @event.organization_id
        format.html { redirect_to event_path(@event), notice: 'El evento fue creado exitosamente.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      updated_params = event_params.except(:sketchs, :organization_charts)
      if @event.update(updated_params)
        
        # attach images
        new_sketchs = params[:event][:sketchs] || []
        new_organization_charts = params[:event][:organization_charts] || []
        new_sketchs.each do |new_sketch|
          @event.sketchs.attach(new_sketch)
        end
        new_organization_charts.each do |new_chart|
          @event.organization_charts.attach(new_chart)
        end

        format.html { redirect_to event_url(@event), notice: 'El evento fue actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def close_event_modal
    @event = Event.find(params[:event_id])
  end

  def close_event
    @event = Event.find(params[:event_id])
    @event.close_and_demobilize(demobilized_params)
    notify_close_event(@event)
    redirect_to event_path(@event), notice: 'Se cerró el incidente.'
  end

  def export_201
    @event = Event.find(params[:event_id])
    respond_to do |format|
      format.pdf do
        pdf = Form201.new(@event, view_context)
        send_data pdf.render, filename: "evento_incidente_201_#{@event.id}.pdf",
                  type: 'application/pdf',
                  disposition: 'inline'
      end
    end
  end

  def export_207
    @event = Event.find(params[:event_id])
    respond_to do |format|
      format.pdf do
        pdf = Form207.new(@event, view_context)
        send_data pdf.render, filename: "evento_incidente_207_#{@event.id}.pdf",
                  type: 'application/pdf',
                  disposition: 'inline'
      end
    end
  end

  def export_211
    @event = Event.find(params[:event_id])
    respond_to do |format|
      format.pdf do
        pdf = Form211.new(@event, view_context)
        send_data pdf.render, filename: "evento_incidente_211_#{@event.id}.pdf",
                  type: 'application/pdf',
                  disposition: 'inline'
      end
    end
  end

  # delete sketch
  def destroy_sketch
    @sketch = @event.sketchs.find(params[:image_id])
    @sketch.purge # delete from ActiveStorage
    redirect_to event_path(@event), notice: 'El croquis fue eliminado correctamente.'
  end

  # delete organization_chart
  def destroy_organization_chart
    @organization_chart = @event.organization_charts.find(params[:image_id])
    @organization_chart.purge # delete from ActiveStorage
    redirect_to event_path(@event), notice: 'El organigrama fue eliminado correctamente.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find_by_id(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(
                                  :name, :kind, :form_start, :event_start, :event_end, :location, :event_nature, :longitude, :latitude,
                                  :threats, :affected_area, :isolation, :objectives, :strategy,
                                  :tactics, :pc_location, :e_location, :entry_route, :egress_route,
                                  :security_message, :communication_channels, :commander, :organization_id,
                                  sketchs: [], organization_charts: [],
                                  event_actions_attributes: [:id, :description, :date, :_destroy]
  )
  end

  def demobilized_params
    params.require(:event).permit(:demobilizing_person, :demobilization_date, :comments)
  end

  def add_index_breadcrumbs
    add_breadcrumbs('Evento e Incidente', events_path)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def resource_request_status_class(rq)
    case rq.status
    when ResourceRequest.status.active
      'border border-success text-success'
    when ResourceRequest.status.canceled
      'border border-danger text-danger'
    when ResourceRequest.status.demobilized
      'border border-primary text-primary'
    else
      'border border-secondary text-secondary'
    end
  end
end

app/views/events/_event.html.erb
<tr>
  <td class="text-start col-4">
    <div class="d-flex">
      <span><%= event.name %></span>
    </div>
  </td>
  <td class="text-start d-none d-md-table-cell"><%= event.commander %></td>
  <td class="text-start d-none d-md-table-cell text-truncate" style="max-width: 100px"><%= event.location %></td>
  <td class="text-start d-none d-md-table-cell"><%= event.event_start.strftime('%d-%m-%Y %H:%M') %></td>
  <td class="text-start d-none d-md-table-cell"><%= event.event_start.strftime('%d-%m-%Y %H:%M') %></td>
  <td class="text-end">
    <%= link_to event_path(event), class: 'text-info me-1 my-0 fs-5', title: 'Editar' do %>
      <span class= "fa fa-pen-to-square"></span>
    <% end unless event.closed %>

    <%= link_to event_path(event), class: 'text-primary me-1 my-0 fs-5', title: 'Ver' do %>
      <span class= "fa fa-eye"></span>
    <% end if event.closed %>
  </td>
</tr>

app/views/events/_form_201.html.erb
<%= simple_form_for @event, wrapper: :floating_labels_form, html: { multipart: true } do |f| %>
  <label class="text-gray-500">Evaluación  Inicial:</label>
  <div class="row">
    <%= f.input :event_nature, wrapper_html: { class: 'mb-3 col-12 col-md' }, input_html: { style: 'height:7rem' } %>
    <%= f.input :threats, wrapper_html: { class: 'mb-3 col-12 col-md' }, input_html: { style: 'height:7rem' } %>
    <%= f.input :affected_area, wrapper_html: { class: 'mb-3 col-12 col-md' }, input_html: { style: 'height:7rem' } %>
  </div>
  <div class="row">
    <%= f.input :objectives, wrapper_html: { class: 'mb-3 col-12 col-md' }, input_html: { style: 'height:10rem' } %>
    <%= f.input :strategy, wrapper_html: { class: 'mb-3 col-12 col-md' }, input_html: { style: 'height:10rem' } %>
    <%= f.input :tactics, wrapper_html: { class: 'mb-3 col-12 col-md' }, input_html: { style: 'height:10rem' } %>
  </div>
  <div class="row">
    <%= f.input :pc_location, wrapper_html: { class: 'mb-3 col-12 col-md' } %>
    <%= f.input :e_location, wrapper_html: { class: 'mb-3 col-12 col-md' } %>
  </div>
  <div class="row">
    <%= f.input :entry_route, wrapper_html: { class: 'mb-3 col-12 col-md' } %>
    <%= f.input :egress_route, wrapper_html: { class: 'mb-3 col-12 col-md' } %>
  </div>
  <div class="row">
    <%= f.input :security_message, wrapper_html: { class: 'mb-3 col-12' } %>
    <%= f.input :communication_channels, wrapper_html: { class: 'mb-3 col-12' } %>
  </div>
  <div class="row">
    <%= f.input :commander, wrapper_html: { class: 'mb-3 col-12' } %>
  </div>
  
  <div class="row">
    <%= f.input :sketchs, wrapper_html: { class: 'mb-3 col-12' }, as: :file, label_html: { class: 'd-block' }, input_html: { multiple: true, class: 'custom-file-input', accept: 'image/*', data: { controller: "file-validation", action: "file-validation#validate", file_validation_target: "input" }  } %>
    <ul class="list-unstyled d-flex flex-wrap">
      <% @event.sketchs.each do |file| %>
        <li class="me-3 mb-3 position-relative">
          <a href="#" data-bs-toggle="modal" data-bs-target="#imageModal-<%= file.id %>">
            <% if file.representable? %>
              <%= image_tag file.representation(resize_to_limit: [100, 100]), class: 'img-thumbnail' %>
            <% else %>
              <span class="text-muted">Imagen no disponible</span>
            <% end %>
          </a>

          <div class="modal fade" id="imageModal-<%= file.id %>" tabindex="-1" aria-labelledby="imageModalLabel-<%= file.id %>" aria-hidden="true">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="imageModalLabel-<%= file.id %>">Mapa Situacional o Croquis</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-center">
                  <% if file.representable? %>
                    <%= image_tag file.representation(resize_to_limit: [800, 800]), class: 'img-fluid' %>
                  <% else %>
                    <p class="text-muted">Imagen no disponible</p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>

          <%= link_to destroy_sketch_event_path(@event, file), method: :delete, data: { confirm: '¿Estás seguro que deseas eliminar esta imagen?' }, class: 'position-absolute top-0 start-100 translate-middle p-1 bg-danger badge rounded-pill fs-6 text-white' do %>
            <i class="fas fa-times"></i>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="row">
    <%= f.input :organization_charts, wrapper_html: { class: 'mb-3 col-12' }, as: :file, label_html: { class: 'd-block' }, input_html: { multiple: true, class: 'custom-file-input', accept: 'image/*', data: { controller: "file-validation", action: "file-validation#validate", file_validation_target: "input" }  } %>
    <ul class="list-unstyled d-flex flex-wrap">
      <% @event.organization_charts.each do |file| %>
        <li class="me-3 mb-3 position-relative">
          <a href="#" data-bs-toggle="modal" data-bs-target="#imageModalChart-<%= file.id %>">
            <% if file.representable? %>
              <%= image_tag file.representation(resize_to_limit: [100, 100]), class: 'img-thumbnail' %>
            <% else %>
              <span class="text-muted">Imagen no disponible</span>
            <% end %>
          </a>

          <div class="modal fade" id="imageModalChart-<%= file.id %>" tabindex="-1" aria-labelledby="imageModalChartLabel-<%= file.id %>" aria-hidden="true">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="imageModalChartLabel-<%= file.id %>">Organigrama</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-center">
                  <% if file.representable? %>
                    <%= image_tag file.representation(resize_to_limit: [800, 800]), class: 'img-fluid' %>
                  <% else %>
                    <p class="text-muted">Imagen no disponible</p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>

          <%= link_to destroy_organization_chart_event_path(@event, file), method: :delete, data: { confirm: '¿Estás seguro que deseas eliminar esta imagen?' }, class: 'position-absolute top-0 start-100 translate-middle p-1 bg-danger badge rounded-pill fs-6 text-white' do %>
            <i class="fas fa-times"></i>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>


  <div class="actions text-end">
    <%= f.button :submit, "Guardar", class: "btn btn-gray-800 mt-2 animate-up-2" %>
    <%= link_to 'Cancelar', events_path, class: 'link-secondary ms-3'%>
  </div>
<% end %>

app/views/events/_form_201_readonly.html.erb
<%= simple_form_for @event, wrapper: :disabled_floating_labels_form do |f| %>
  <label class="text-gray-500">Evaluación  Inicial:</label>
  <div class="row">
    <%= f.input :event_nature, wrapper_html: { class: 'mb-3 col-12 col-md' }, input_html: { style: 'height:7rem' } %>
    <%= f.input :threats, wrapper_html: { class: 'mb-3 col-12 col-md' }, input_html: { style: 'height:7rem' } %>
    <%= f.input :affected_area, wrapper_html: { class: 'mb-3 col-12 col-md' }, input_html: { style: 'height:7rem' } %>
  </div>
  <div class="row">
    <%= f.input :objectives, wrapper_html: { class: 'mb-3 col-12 col-md' }, input_html: { style: 'height:10rem' } %>
    <%= f.input :strategy, wrapper_html: { class: 'mb-3 col-12 col-md' }, input_html: { style: 'height:10rem' } %>
    <%= f.input :tactics, wrapper_html: { class: 'mb-3 col-12 col-md' }, input_html: { style: 'height:10rem' } %>
  </div>
  <div class="row">
    <%= f.input :pc_location, wrapper_html: { class: 'mb-3 col-12 col-md' } %>
    <%= f.input :e_location, wrapper_html: { class: 'mb-3 col-12 col-md' } %>
  </div>
  <div class="row">
    <%= f.input :entry_route, wrapper_html: { class: 'mb-3 col-12 col-md' } %>
    <%= f.input :egress_route, wrapper_html: { class: 'mb-3 col-12 col-md' } %>
  </div>
  <div class="row">
    <%= f.input :security_message, wrapper_html: { class: 'mb-3 col-12' } %>
    <%= f.input :communication_channels, wrapper_html: { class: 'mb-3 col-12' } %>
  </div>
  <div class="row">
    <%= f.input :commander, wrapper_html: { class: 'mb-3 col-12' } %>
  </div>
  <div class="row">
    <ul>
      <% f.object.sketchs.each do |file| %>
        <li>
          <%= image_tag file.representation(resize_to_limit: [100, 100])  if file.representable? %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="row">
    <ul>
      <% f.object.organization_charts.each do |file| %>
        <li>
          <%= image_tag file.representation(resize_to_limit: [100, 100])  if file.representable? %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/events/close_event_modal.html.erb
<%= render 'remote_modal', title: "Cierre del Incidente" do %>
  <%= simple_form_for @event, url: event_close_event_path(@event), method: :post, wrapper: :floating_labels_form do |f| %>
    <div class="row g-0 mb-3">
      <div class="col-lg-6 pe-1">
        <div class="form-floating mb-3">
          <%= f.input_field :demobilization_date,
                            as: :string,
                            class: 'form-control',
                            data: {
                              controller: 'flatpickr',
                              enable_time: 'true',
                              flatpickr_date_format: 'd-m-Y H:i',
                              flatpickr_alt_input: false,
                              flatpickr_default_date: Time.zone.now.strftime("%d-%m-%Y %H:%M")
                            } %>
          <label>Fecha y hora de desmovilización</label>
        </div>
      </div>

      <div class="col-lg-6 ps-1">
        <%= f.input :demobilizing_person %>
      </div>
    </div>

    <div class="row g-0 mb-3">
      <%= f.input :comments, as: :text, input_html: { value: '' } %>
    </div>

    <p class="text-danger">
      <b>AVISO:</b> Una vez cerrado el incidente, todos los recursos activos se desmovilizarán y no se podrá modificar dicho incidente.
    </p>
    <div class="actions text-start">
      <%= f.button :submit, "Desmovilizar y cerrar", class: "btn btn-gray-800 mt-2 animate-up-2" %>
    </div>

  <% end %>
<% end %>

app/views/events/create.turbo_stream.erb
<%= turbo_stream.prepend "events", @event %>
<%= turbo_stream.update Event.new, "" %>
<%= turbo_stream.update "toast_notice", partial: "layouts/toast", locals: {alert: alert, notice: notice } %>

app/views/events/index.html.erb
<div class="col-12 mb-4">
  <div class="card border-0 shadow components-section">
    <div class="card-header bg-white border-0 pb-0">
      <div class="d-flex flex-wrap flex-md-nowrap align-items-center py-4">
        <h2 class="h4 m-0 me-auto">Eventos e Incidentes</h2>
        <%= link_to "Programar Evento", new_event_path(kind: Event.kind.event), class: 'btn btn-outline-primary mt-2 mx-2 animate-up-2' %>
        <%= link_to "Crear Incidente", new_event_path, class: 'btn btn-gray-800 mt-2 animate-up-2' %>
      </div>
    </div>
    <%= render 'search_form', q: @q %>
    <div class="card-body pt-0 pb-4">
      <div class="table-responsive">
        <table class="table table-centered table-nowrap mb-0 rounded">
          <thead class="thead-light">
          <tr>
            <th class="border-0 rounded-start"><%= sort_link(@q, :name, 'Nombre') %></th>
            <th class="border-0 d-none d-md-table-cell"><%= sort_link(@q, :commander, 'Comandante') %></th>
            <th class="border-0 d-none d-md-table-cell"><%= sort_link(@q, :location, 'Lugar') %></th>
            <th class="border-0 d-none d-md-table-cell"><%= sort_link(@q, :event_start, 'Inicio', default_order: :desc) %></th>
            <th class="border-0 d-none d-md-table-cell"><%= sort_link(@q, :event_end, 'Fin') %></th>
            <th class="border-0 rounded-end"></th>
          </tr>
          </thead>
          <tbody>
          <%= render @events %>
          </tbody>
        </table>
      </div>
    </div>
    <%= paginate @events , theme: 'bootstrap-5',
                 pagination_class: "pagination-sm flex-wrap justify-content-center"%>
  </div>
</div>

app/views/events/show.html.erb
<div class="col-12 mb-4" xmlns="http://www.w3.org/1999/html">
  <div class="card border-0 shadow components-section">
    <div class="card-header bg-white border-0 pb-0">
      <div class="d-flex align-items-center flex-wrap">
        <%= link_to event_export_201_path(@event, format: "pdf"), :class => 'btn btn-outline-primary d-inline-flex align-items-center me-1 my-0', title: '201', target: :_blank do %>
          <span class= "fa fa-file-pdf me-2"></span>
          201
        <% end %>
        <%= link_to event_export_207_path(@event, format: "pdf"), :class => 'btn btn-outline-primary d-inline-flex align-items-center me-1 my-0', title: '201', target: :_blank do %>
          <span class= "fa fa-file-pdf me-2"></span>
          207
        <% end %>
        <%= link_to event_export_211_path(@event, format: "pdf"), :class => 'btn btn-outline-primary d-inline-flex align-items-center me-auto my-0', title: '201', target: :_blank do %>
          <span class= "fa fa-file-pdf me-2"></span>
          211
        <% end %>

        <%= link_to edit_event_path(@event), :class => 'btn btn-outline-info me-1 my-0', title: 'Editar encabezado' do %>
          <span class= "fa fa-pen-to-square"></span>
        <% end unless @event.closed %>

        <%= button_to "Cerrar #{@event.kind.text}", event_close_event_modal_path(@event),
                      method: :get,
                      data: { turbo_frame: 'remote_modal' },
                      class: 'btn btn-danger' unless @event.closed %>
      </div>

      <div class="d-flex justify-content-between align-items-center mt-3">
        <strong class="h5">
          <%= @event.name %>
          <%- if @event.longitude %>
            <a href="https://maps.google.com/?q=<%= @event.latitude %>,<%= @event.longitude %>" target="_blank" title="Abrir mapa" class="ms-2 text-info"><i class="fa-solid fa-map-location-dot"></i></a>
          <% end %>
        </strong>
        <div><%= @event.event_start.strftime('%d-%m-%Y %H:%M') %> <%= " - #{@event.event_end.strftime('%d-%m-%Y %H:%M')}" if @event.closed %></div>
      </div>
      <div>Asignado a: <%= @event.organization&.name %></div>
      <div><%= @event.location %></div>
    </div>
    <div class="card-body pb-4">
      <div class="row">
        <div class="col-12">
          <!-- Tab -->
          <nav>
            <div class="nav nav-tabs mb-4" id="nav-tab" role="tablist">
              <a class="nav-item nav-link active" id="nav-201-tab" data-bs-toggle="tab" href="#nav-event" role="tab" aria-controls="nav-event" aria-selected="true">201-1 <span class="d-none d-md-inline">- <%= @event.kind.text %></span></a>
              <a class="nav-item nav-link" id="nav-201-actions-tab" data-bs-toggle="tab" href="#nav-actions" role="tab" aria-controls="nav-actions" aria-selected="false">201-2 <span class="d-none d-md-inline">- Acciones</span></a>
              <a class="nav-item nav-link" id="nav-207-tab" data-bs-toggle="tab" href="#nav-victims" role="tab" aria-controls="nav-victims" aria-selected="false">207 <span class="d-none d-md-inline">- Víctimas</span></a>
              <a class="nav-item nav-link" id="nav-211-tab" data-bs-toggle="tab" href="#nav-resources" role="tab" aria-controls="nav-resources" aria-selected="false">211-1 <span class="d-none d-md-inline">- Solicitud de Recursos</span></a>
              <a class="nav-item nav-link" id="nav-211-control-tab" data-bs-toggle="tab" href="#nav-resources-control" role="tab" aria-controls="nav-resources-control" aria-selected="false">211-2 <span class="d-none d-md-inline">- Control de Recursos</span></a>
            </div>
          </nav>
          <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-event" role="tabpanel" aria-labelledby="nav-201-tab">
              <%= render 'form_201' unless @event.closed %>
              <%= render 'form_201_readonly' if @event.closed %>
            </div>
            <div class="tab-pane fade" id="nav-actions" role="tabpanel" aria-labelledby="nav-201-actions-tab">
              <%= render 'event_actions/index' %>
            </div>
            <div class="tab-pane fade" id="nav-victims" role="tabpanel" aria-labelledby="nav-207-tab">
              <%= render 'victims/index' %>
            </div>
            <div class="tab-pane fade" id="nav-resources" role="tabpanel" aria-labelledby="nav-211-tab">
              <%= render 'resource_requests/index' %>
            </div>
            <div class="tab-pane fade" id="nav-resources-control" role="tabpanel" aria-labelledby="nav-211-control-tab">
              <%= render 'assist_requests/index' %>
            </div>
          </div>
          <!-- End of tab -->
        </div>
      </div>
    </div>
  </div>
</div>