config/routes.rb
Rails.application.routes.draw do
  #mount ActionCable.server => '/cable'

  # Para el restablecimiento de contraseña desde el login
  devise_for :users, :skip => [:registrations], controllers: {
    registrations: 'registrations',
    passwords: 'passwords'  # Opcional: si quieres personalizar el controlador de contraseñas
  }

  # Para el cambio de contraseña desde el perfil
  as :user do
    get 'users/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'registrations#update', :as => 'user_registration'
  end

  # Luego tus rutas personalizadas
  resources :users, only: [:update]
  get 'users/profile'
  get 'users/change_password_modal', to: 'users#change_password_modal'

  resources :events, except: [:destroy] do
    resources :victims, except: [:index, :show]
    resources :event_actions, except: [:index, :show]
    resources :resource_requests, except: [:destroy, :show, :edit, :update] do
      get :cancel
    end
    member do
      delete 'sketch/:image_id', to: 'events#destroy_sketch', as: 'destroy_sketch'
      delete 'organization_chart/:image_id', to: 'events#destroy_organization_chart', as: 'destroy_organization_chart'
    end
    get :export_201
    get :export_207
    get :export_211
    get :close_event_modal
    post :close_event
  end

  resources :resource_requests, only: [:index, :new, :create] do
    resources :assist_requests, only: [:new, :create]
  end

  resources :assist_requests, only: [] do
    collection do
      post :create_assist
    end
    get :arrive_modal
    put :arrive
    get :demobilize_modal
    put :demobilize
    get :state_modal
    put :change_state
  end

  resources :user_permissions, :except => [:destroy, :show]

  resources :resources, :except => [:destroy, :show] do
    collection do
      get :search_resources
    end
  end

  resources :organizations, :except => [:destroy] do
    resources :resource_per_organizations, :except => [:destroy, :show]
  end

  resources :notifications, only: [:index, :show] do
    collection do
      get :mark_as_read
    end
  end

  get 'reports/report'
  root to: 'dashboard#index'
  get 'dashboard/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/resources/_form.html.erb
<%= simple_form_for @resource do |f| %>
  <div class="col-lg-6">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :kind, prompt: 'Selecciona un tipo', input_html: { class: 'form-select' } %>
    <%= f.input :active %>

    <div class="actions text-start">
      <%= f.button :submit, "Guardar", class: "btn btn-gray-800 mt-2 animate-up-2" %>
      <%= link_to 'Cancelar', resources_path, class: 'link-secondary ms-3'%>
    </div>
  </div>
<% end %>

app/views/resources/_search_form.html.erb
<%= search_form_for @q do |f| %>
  <div class="col-12 mb-4" xmlns="http://www.w3.org/1999/html">
    <div class="card border-0 components-section" >
      <div class="card-header bg-white border-0 pb-0" >
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center row g-0">
          <div class=" col-lg-4 form-floating me-1">
            <%= f.search_field :name_i_cont_any , class: 'form-control', placeholder: 'Nombre'%>
            <%= f.label :name, for:'name_i_cont_any' %>
          </div>
          <div class="col-lg-3 form-floating me-1">
            <%= f.select :kind_eq, Resource.kind.options.unshift(['Todos', nil]), {}, { class: 'form-select' } %>
            <%= f.label :kind, for: 'kind_eq' %>
          </div>
          <%= f.button nil, class: "btn btn-secondary col-lg-1 ms-auto" do %>
            <i class="fas fa-search"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/resources/_table.html.erb
<% resources.each do |resource| %>
  <tr>
    <td class="text-start col-4">
      <div class="d-flex align-items-center">
        <div class="dot rounded-circle me-1 <%= resource.active?? 'bg-success':'bg-secondary' %>"></div>
        <%= resource.name %>
      </div>
    </td>
    <td class="text-start d-none d-md-table-cell"><%= resource.kind_text %></td>
    <td class="text-start d-none d-md-table-cell text-truncate" style="max-width: 100px"><%= resource.description %></td>
    <td class="text-start" style="max-width: 100px"><%= resource.total %></td>
    <td class="text-end">
      <%= link_to edit_resource_path(resource), class: 'text-info me-1 my-0 fs-5', title: 'Editar' do %>
        <span class= "fa fa-pen-to-square"></span>
      <% end if can? :edit, resource %>
    </td>
  </tr>
<% end %>

app/views/resources/edit.html.erb
<div class="col-12 mb-4">
  <div class="card border-0 shadow components-section">
    <div class="card-header bg-white border-0 pb-0">
      <h2 class="h4">Editar Recurso</h2>
    </div>
    <div class="card-body pb-4">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/resources/index.html.erb
<div class="col-12 mb-4">
  <div class="card border-0 shadow components-section">
    <div class="card-header bg-white border-0 pb-0">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
        <h2 class="h4 m-0">Recursos</h2>
        <%= link_to "Crear Recurso", new_resource_path, class: 'btn btn-gray-800 mt-2 animate-up-2' if can? :create, Resource%>
      </div>
    </div>
    <%= render 'resources/search_form', q: @q %>
    <div class="card-body pt-0 pb-4">
      <div class="table-responsive">
        <table class="table table-centered table-nowrap mb-0 rounded">
          <thead class="thead-light">
            <tr>
              <th class="border-0 rounded-start"><%= sort_link(@q, :name, 'Nombre', default_order: :desc) %></th>
              <th class="border-0 d-none d-md-table-cell"><%= sort_link(@q, :kind, 'Tipo', default_order: :desc) %></th>
              <th class="border-0 d-none d-md-table-cell">Descripci&oacute;n</th>
              <th class="border-0">Total</th>
              <th class="border-0 rounded-end"></th>
            </tr>
          </thead>
          <tbody>
          <%= render 'table', resources: @resources %>
          </tbody>
        </table>
      </div>
    </div>
    <%= paginate @resources , theme: 'bootstrap-5',
                 pagination_class: "pagination-sm flex-wrap justify-content-center"%>
  </div>
</div>

app/views/resources/new.html.erb
<div class="col-12 mb-4">
  <div class="card border-0 shadow components-section">
    <div class="card-header bg-white border-0 pb-0">
      <h2 class="h4">Crear Recurso</h2>
    </div>
    <div class="card-body pb-4">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/resources/search_resources.html.erb
<div class="row" data-controller="map">
  <div class="col-12 col-xl-4 d-flex flex-column height-90vh">
    <%= render 'resources/search_resources/card' %>
  </div>
  <div class="col-12 col-xl-8">
    <%- @resources_per_organization&.pluck(:organization_id)&.uniq&.each do |org_id| %>
      <%- org = Organization.find_by_id org_id %>
      <div data-map-target="marker" data-id="<%= org.id %>" data-lat="<%= org.latitude %>" data-lng="<%= org.longitude %>" data-title="<%= org.name %>" data-icon="<%= asset_path("map_icons/#{org.custom_icon || 'icon1.svg'}") %>" data-url="<%= organization_path(org) %>"></div>
    <% end %>
    <div data-map-target="map" class="height-90vh"></div>
  </div>
</div>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>