config/routes.rb
Rails.application.routes.draw do
  #mount ActionCable.server => '/cable'

  # Para el restablecimiento de contraseña desde el login
  devise_for :users, :skip => [:registrations], controllers: {
    registrations: 'registrations',
    passwords: 'passwords'  # Opcional: si quieres personalizar el controlador de contraseñas
  }

  # Para el cambio de contraseña desde el perfil
  as :user do
    get 'users/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'registrations#update', :as => 'user_registration'
  end

  # Luego tus rutas personalizadas
  resources :users, only: [:update]
  get 'users/profile'
  get 'users/change_password_modal', to: 'users#change_password_modal'

  resources :events, except: [:destroy] do
    resources :victims, except: [:index, :show]
    resources :event_actions, except: [:index, :show]
    resources :resource_requests, except: [:destroy, :show, :edit, :update] do
      get :cancel
    end
    member do
      delete 'sketch/:image_id', to: 'events#destroy_sketch', as: 'destroy_sketch'
      delete 'organization_chart/:image_id', to: 'events#destroy_organization_chart', as: 'destroy_organization_chart'
    end
    get :export_201
    get :export_207
    get :export_211
    get :close_event_modal
    post :close_event
  end

  resources :resource_requests, only: [:index, :new, :create] do
    resources :assist_requests, only: [:new, :create]
  end

  resources :assist_requests, only: [] do
    collection do
      post :create_assist
    end
    get :arrive_modal
    put :arrive
    get :demobilize_modal
    put :demobilize
    get :state_modal
    put :change_state
  end

  resources :user_permissions, :except => [:destroy, :show]

  resources :resources, :except => [:destroy, :show] do
    collection do
      get :search_resources
    end
  end

  resources :organizations, :except => [:destroy] do
    resources :resource_per_organizations, :except => [:destroy, :show]
  end

  resources :notifications, only: [:index, :show] do
    collection do
      get :mark_as_read
    end
  end

  get 'reports/report'
  root to: 'dashboard#index'
  get 'dashboard/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/resource_per_organization.rb
class ResourcePerOrganization < ApplicationRecord
  belongs_to :resource
  belongs_to :organization

  #validations
  validates :organization, :resource, presence: true
  validates :resource, uniqueness: { scope: :organization }
  validates :quantity, numericality: { greater_than: 0 }

  #scopes
  scope :by_organization, -> (organization){ where(organization_id: organization&.id) }
  scope :quantity_gt_quantity_used, -> (val=nil){ where('quantity > quantity_used') } # for ransack filter

  def self.ransackable_attributes(auth_object = nil)
    %w[resource]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[organization resource]
  end

  def self.ransackable_scopes(auth_object = nil)
    %i(quantity_gt_quantity_used)
  end
end

app/controllers/resource_per_organizations_controller.rb
class ResourcePerOrganizationsController < ApplicationController
  load_and_authorize_resource
  before_action :add_index_breadcrumbs, only: [:show, :edit, :new]

  # GET /resource_per_organizations or /resource_per_organizations.json
  def index
    @q = ResourcePerOrganization.by_organization(@organization).ransack(params[:q] || {})
    @resource_per_organizations = @q.result.page(params[:page]).per(@per_page)
    add_breadcrumbs("Recursos por Organización")
  end

  # GET /resource_per_organizations/1 or /resource_per_organizations/1.json
  def show; end

  # GET /resource_per_organizations/new
  def new
    @resource_per_organization = ResourcePerOrganization.new
    add_breadcrumbs("Nuevo")
  end

  # GET /resource_per_organizations/1/edit
  def edit
    add_breadcrumbs(@organization.name, organization_resource_per_organizations_path(@organization))
    add_breadcrumbs('Editar')
  end

  # POST /resource_per_organizations or /resource_per_organizations.json
  def create
    @resource_per_organization = @organization.resource_per_organizations.new(resource_per_organization_params)

    respond_to do |format|
      if @resource_per_organization.save
        format.html { redirect_to organization_resource_per_organizations_path(@resource_per_organization.organization), notice: "El recurso fue creado exitosamente." }
        format.json { render :show, status: :created, location: @resource_per_organization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resource_per_organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resource_per_organizations/1 or /resource_per_organizations/1.json
  def update
    respond_to do |format|
      if @resource_per_organization.update(edit_resource_per_organization_params)
        format.html { redirect_to organization_resource_per_organizations_path(@resource_per_organization.organization), notice: "El recurso fue actualizado exitosamente." }
        format.json { render :show, status: :ok, location: @resource_per_organization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resource_per_organization.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Only allow a list of trusted parameters through.
  def resource_per_organization_params
    params.require(:resource_per_organization).permit(:organization_id, :resource_id, :quantity)
  end

  def edit_resource_per_organization_params
    params.require(:resource_per_organization).permit(:quantity)
  end

  def add_index_breadcrumbs
    add_breadcrumbs('Recurso por Organización', organization_resource_per_organizations_path(@organization))
  end
end

app/helpers/resource_per_organizations_helper.rb
module ResourcePerOrganizationsHelper
end

app/views/resource_per_organizations/_form.html.erb
<%= simple_form_for [@organization, @resource_per_organization] do |f| %>
  <div class="col-lg-6">
    <%= f.association :resource,
                      collection: Resource.active_resources,
                      prompt: 'Selecciona un recurso',
                      input_html: {
                        data: { controller: 'ts--select' }
                      } %>
    <%= f.input :quantity, input_html: { min: '0' } %>
    <div class="actions text-start">
      <%= f.button :submit, "Guardar", class: "btn btn-gray-800 mt-2 animate-up-2" %>
      <%= link_to 'Cancelar', organization_resource_per_organizations_path(@organization), class: 'link-secondary ms-3'%>
    </div>
  </div>
<% end %>

app/views/resource_per_organizations/_search_form.html.erb
<%= search_form_for(@q, url: organization_resource_per_organizations_path(@organization), method: :get) do |f| %>
  <div class="col-12 mb-4" xmlns="http://www.w3.org/1999/html">
    <div class="card border-0 components-section" >
      <div class="card-header bg-white border-0 pb-0" >
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center row g-0">
          <div class=" col-lg-4 form-floating me-1">
            <%= f.search_field :resource_name_i_cont_any , class: 'form-control', placeholder: 'Nombre'%>
            <%= f.label :name, 'Recurso', for:'resource_name_i_cont_any' %>
          </div>
          <div class="col-lg-3 form-floating me-1">
            <%= f.select :resource_kind_eq, Resource.kind.options.unshift(['Todos', nil]), {}, { class: 'form-select' } %>
            <%= f.label :kind, 'Tipo de Recurso', for: 'resource_kind_eq' %>
          </div>
          <%= f.button nil, class: "btn btn-secondary col-lg-1 ms-auto" do %>
            <i class="fas fa-search"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/resource_per_organizations/_table.html.erb
<% resources.each do |rpo| %>
  <tr>
    <td class="text-start col-4"><%= rpo.resource.name %></td>
    <td class="text-start"><%= rpo.quantity %></td>
    <td class="text-start"><%= rpo.quantity - rpo.quantity_used %></td>
    <td class="text-end">
      <%= link_to edit_organization_resource_per_organization_path(@organization, rpo), class: 'text-info me-1 my-0 fs-5', title: 'Editar' do %>
        <span class= "fa fa-pen-to-square"></span>
      <% end if can? :edit, rpo %>
    </td>
  </tr>
<% end %>

app/views/resource_per_organizations/edit.html.erb
<div class="col-12 mb-4">
  <div class="card border-0 shadow components-section">
    <div class="card-header bg-white border-0 pb-0">
      <h2 class="h4">Editar Recurso - <%= @organization&.name %></h2>
    </div>
    <div class="card-body pb-4">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/resource_per_organizations/index.html.erb
<div class="col-12 mb-4">
  <div class="card border-0 shadow components-section">
    <div class="card-header bg-white border-0 pb-0">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
        <h2 class="h4 m-0">Recursos - <%= @organization&.name %></h2>
        <%= link_to "Agregar Recurso", new_organization_resource_per_organization_path(@organization), class: 'btn btn-gray-800 mt-2 animate-up-2' if can? :create, ResourcePerOrganization %>
      </div>
    </div>
    <%= render 'search_form', q: @q %>
    <div class="card-body pt-0 pb-4">
      <div class="table-responsive">
        <table class="table table-centered table-nowrap mb-0 rounded">
          <thead class="thead-light">
          <tr>
            <th class="border-0 rounded-start">Nombre</th>
            <th class="border-0">Cantidad</th>
            <th class="border-0">Disponible</th>
            <th class="border-0 rounded-end"></th>
          </tr>
          </thead>
          <tbody>
          <%= render 'table', resources: @resource_per_organizations %>
          </tbody>
        </table>
      </div>
    </div>
    <%= paginate @resource_per_organizations , theme: 'bootstrap-5',
                 pagination_class: "pagination-sm flex-wrap justify-content-center"%>
  </div>
</div>

app/views/resource_per_organizations/new.html.erb
<div class="col-12 mb-4">
  <div class="card border-0 shadow components-section">
    <div class="card-header bg-white border-0 pb-0">
      <h2 class="h4">Crear Recurso - <%= @organization&.name %></h2>
    </div>
    <div class="card-body pb-4">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/resource_per_organizations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_resource_per_organization_path(@resource_per_organization) %> |
<%= link_to 'Back', resource_per_organizations_path %>